### ISSUE TITLE
app server

### ISSUE THREAD

**Issue by ouhouhsami** [MTES-MCT/aides-territoires#5]
Hello, 
lorsque je fais 
```yarn dev```
j'obtiens cette erreur là : 
```
goldszmidt@sam~/sam/pro/dev/aides-territoires/server $ yarn dev
yarn run v1.7.0
$ nodemon src/index.js
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/index.js`
Error: Invalid schema, expected `mongodb` or `mongodb+srv`
    at module.exports (/Users/goldszmidt/sam/pro/dev/aides-territoires/server/node_modules/mongodb/lib/url_parser.js:21:21)
    at Promise (/Users/goldszmidt/sam/pro/dev/aides-territoires/server/node_modules/mongoose/lib/connection.js:338:5)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/Users/goldszmidt/sam/pro/dev/aides-territoires/server/node_modules/mongoose/lib/connection.js:337:19)
    at Mongoose.connect (/Users/goldszmidt/sam/pro/dev/aides-territoires/server/node_modules/mongoose/lib/index.js:207:15)
    at connectToMongodb (/Users/goldszmidt/sam/pro/dev/aides-territoires/server/src/index.js:24:19)
    at Object.<anonymous> (/Users/goldszmidt/sam/pro/dev/aides-territoires/server/src/index.js:14:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
[nodemon] clean exit - waiting for changes before restart
```
est-ce à dire qu'il faudrait installer mongodb ?

Merci

**Comment by nyl-auster** [comment]
j'ai modifié les instructions du README concernant ce point et la gestion des variables secrètes
